### ISSUE TITLE
Tried to follow the tutorial and figure it out from the docs, but..

### ISSUE THREAD

**Issue by 7ojo** [jhthorsen/mojolicious-plugin-openapi#13]
Mojolicious::Plugin::OpenAPI::Guides::Tutorial

I got my rest demo app running and copy pasted the spesification json (note: there is extra bracket on line 14 which give syntax error)

For the `MyApp::Controller::Pet` I had to add "`use Mojo::Base 'Mojolicious::Controller'`", because of `error: Class "MyApp::Controller::Pet" is not a controller`

After that I'm getting this error:
Log output:
`[warn] OpenAPI >>> GET /api/pets [{"message":"Expected object - got array.","path":"\/"}]`

Browser output:
`{"errors":[{"message":"Expected object - got array.","path":"\/"}],"status":500}`

And I don't have a clue why this isn't working. Any help on this? :) 

I tried changing `$c->render(openapi  => $output)` to `$c->render(json => $output)` to skip validation, but it doesn't had any effect. Got the same error.

Mojolicious is very new for me so this can be some basic stuff that I just don't know.

**Comment by jhthorsen** [comment]
Hi! Thanks for reporting in. To be honest, I didn't expect the tutorial code to be copy-pasted, so I never checked the quality of it myself. I've now copied the code into a test, so the new version should be copy-paste'able.

Enjoy!

You can see the changes here abfbc66af1d3ee5a991129632b1b089435376117 and the new tutorial here: https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/abfbc66af1d3ee5a991129632b1b089435376117/lib/Mojolicious/Plugin/OpenAPI/Guides/Tutorial.pod

The new release will soon also be available on CPAN.

You can join #swagger on irc.perl.org if you have any questions. You're more likely to get better help there, since github is not a support channel. My nick on irc.perl.org is "batman".
