### ISSUE TITLE
Swagger-ui support

### ISSUE THREAD

**Issue by sudo-batman** [jhthorsen/mojolicious-plugin-openapi#139]
Just a question-
Does this plugin provide 'swagger-ui' also(like django or flask) or is there any plan to include that in future?

I found swagger ui support in Dancer::Plugin::Swagger. Is there something for Mojolicious also?

**Comment by jhthorsen** [comment]
It does not include any UI, and there's no plan to include one either. I think it's a great mistake to include a third party tool, because then I have to monitor and build a new version of mojolicious-plugin-openapi each time the tool is updated.

M::P::OpenAPI does however include a document render, since there's no alternative in the wild - that I know of. (And yes: I do know of third party doc renderers, but none that can be printed)

**Comment by sudo-batman** [comment]
Sound good. Thank you
