### ISSUE TITLE
204 No Content response hangs for 15 seconds

### ISSUE THREAD

**Issue by chandwer** [jhthorsen/mojolicious-plugin-openapi#18]
For example if I call,

`$c->render(openapi => {}, status => 204);`

It takes 15 seconds to return 204 No Content.

If I call,

`$c->render( status => 204 );`

I get this back without any lag time,

`{
  "errors": [
    {
      "message": "Not implemented.",
      "path": "/"
    }
  ],
  "status": 501
}`

**Comment by chandwer** [comment]
Well I guess it doesn't make sense to involve openapi for validation if it's just no content so maybe this isn't a bug. This just came up because I have a standard response handling method that takes a status from the caller.

**Comment by jhthorsen** [comment]
Thanks for reporting in!

Could you please provide a sample specification and code for this? Please keep the sample to a minimum.

**Comment by kivilahtio** [comment]
chandwer, I got this working by 
`$c->render(openapi => undef, status => 204);`

In the swagger2 spec, have something like this:
```
      responses:
        204:
          description: Deletion ok
```

**Comment by jhthorsen** [comment]
This test shows that this works as expected already: https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/master/t/empty-string.t

Note that `{}` is a JSON object, and not empty string at all. Nevertheless, It seems like mojolicious omits the body on 204, so it shouldn't matter. I think the bug is somewhere else in your application. Maybe you call `render()` twice?
